import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parsePackageLock, parseYarnLock, findDuplicates } from '../lib/lockfile.js';

test('parsePackageLock handles lockfileVersion 3 packages map', () => {
  const lock = {
    lockfileVersion: 3,
    packages: {
      '': { name: 'root' },
      'node_modules/foo': { version: '1.0.0' },
      'node_modules/bar': { version: '2.0.0' },
      'node_modules/bar/node_modules/foo': { version: '1.5.0' },
    },
  };
  const map = parsePackageLock(lock);
  assert.deepEqual([...map.get('foo').keys()].sort(), ['1.0.0', '1.5.0']);
  assert.equal(map.get('foo').get('1.0.0'), 1);
  assert.deepEqual([...map.get('bar').keys()], ['2.0.0']);
});

test('parsePackageLock handles lockfileVersion 1 nested dependencies', () => {
  const lock = {
    lockfileVersion: 1,
    dependencies: {
      foo: { version: '1.0.0', dependencies: { qux: { version: '0.1.0' } } },
      bar: { version: '2.0.0', dependencies: { qux: { version: '0.2.0' } } },
    },
  };
  const map = parsePackageLock(lock);
  assert.deepEqual([...map.get('qux').keys()].sort(), ['0.1.0', '0.2.0']);
});

test('parsePackageLock skips entries without versions', () => {
  const lock = { packages: { 'node_modules/link': { link: true, resolved: 'src' } } };
  const map = parsePackageLock(lock);
  assert.equal(map.size, 0);
});

test('parseYarnLock parses v1 entries including scoped and quoted descriptors', () => {
  const text = [
    '# THIS IS AN AUTOGENERATED FILE',
    '',
    'moment@^2.0.0, moment@~2.29.0:',
    '  version "2.29.4"',
    '  resolved "https://registry.yarnpkg.com/moment/-/moment-2.29.4.tgz"',
    '',
    '"@scope/pkg@^1.0.0":',
    '  version "1.2.3"',
    '',
    'single@^1.0.0:',
    '  version "1.0.0"',
    'single@^2.0.0:',
    '  version "2.0.0"',
    '',
  ].join('\n');
  const map = parseYarnLock(text);
  assert.deepEqual([...map.get('moment').keys()], ['2.29.4']);
  assert.deepEqual([...map.get('@scope/pkg').keys()], ['1.2.3']);
  assert.deepEqual([...map.get('single').keys()].sort(), ['1.0.0', '2.0.0']);
});

test('findDuplicates reports only multi-version packages with counts', () => {
  const lock = {
    packages: {
      'node_modules/foo': { version: '1.0.0' },
      'node_modules/a/node_modules/foo': { version: '2.1.0' },
      'node_modules/b/node_modules/foo': { version: '1.0.0' },
      'node_modules/solo': { version: '3.0.0' },
    },
  };
  const dupes = findDuplicates(parsePackageLock(lock));
  assert.equal(dupes.length, 1);
  assert.equal(dupes[0].name, 'foo');
  assert.deepEqual(dupes[0].versions, ['1.0.0', '2.1.0']);
  assert.equal(dupes[0].occurrences, 3);
});

test('findDuplicates sorts by version count desc then name', () => {
  const map = new Map([
    ['zzz', new Map([['1.0.0', 1], ['2.0.0', 1]])],
    ['aaa', new Map([['1.0.0', 1], ['2.0.0', 1], ['3.0.0', 1]])],
    ['mmm', new Map([['1.0.0', 1], ['2.0.0', 1]])],
  ]);
  const dupes = findDuplicates(map);
  assert.deepEqual(dupes.map((d) => d.name), ['aaa', 'mmm', 'zzz']);
});
