/**
 * Static knowledge base of commonly bloated or deprecated packages with
 * lighter replacements. Sizes are approximate min+gzip KB (bundlephobia-ish,
 * rounded). Only direct dependencies are matched against this table.
 */
export const KB = {
  moment: { kb: 72, swap: 'dayjs (2KB, moment-compatible API) or date-fns or native Intl', note: 'maintenance mode since 2020; locale files bloat bundles' },
  'moment-timezone': { kb: 180, swap: 'Intl.DateTimeFormat with the timeZone option (built in)', note: 'ships a copy of the tz database' },
  lodash: { kb: 72, swap: 'native ES methods, or per-method imports (lodash/get)', note: 'most helpers exist natively since ES2015+' },
  underscore: { kb: 20, swap: 'native ES methods' },
  request: { kb: 130, swap: 'native fetch (Node >= 18) or undici', deprecated: true, note: 'deprecated since Feb 2020' },
  'request-promise': { kb: 140, swap: 'native fetch (Node >= 18)', deprecated: true, note: 'built on deprecated request' },
  'request-promise-native': { kb: 140, swap: 'native fetch (Node >= 18)', deprecated: true, note: 'built on deprecated request' },
  'har-validator': { kb: 60, swap: 'nothing — it only arrives via deprecated request', deprecated: true },
  axios: { kb: 30, swap: 'native fetch (Node >= 18) or undici for advanced use' },
  'node-fetch': { kb: 25, swap: 'native fetch (Node >= 18)' },
  got: { kb: 45, swap: 'native fetch + undici for retries/hooks' },
  superagent: { kb: 55, swap: 'native fetch (Node >= 18)' },
  uuid: { kb: 12, swap: 'crypto.randomUUID() (Node >= 14.17) for v4' },
  'node-uuid': { kb: 10, swap: 'crypto.randomUUID()', deprecated: true, note: 'renamed to uuid long ago; WebCrypto supersedes both' },
  rimraf: { kb: 6, swap: 'fs.rm(path, { recursive: true, force: true }) (Node >= 14.14)' },
  del: { kb: 20, swap: 'fs.rm(path, { recursive: true, force: true })', note: 'pulls a large transitive tree (globby)' },
  mkdirp: { kb: 5, swap: 'fs.mkdir(path, { recursive: true }) (Node >= 10)' },
  chalk: { kb: 10, swap: 'picocolors (2KB, zero deps) or node:util styleText (Node >= 20.12)' },
  colors: { kb: 12, swap: 'picocolors', note: '2022 maintainer sabotage incident; picocolors is safer' },
  'cross-env': { kb: 4, swap: 'node --env-file (Node >= 20.6) or inline env vars' },
  dotenv: { kb: 8, swap: 'node --env-file (Node >= 20.6)' },
  minimist: { kb: 8, swap: 'node:util parseArgs (Node >= 18.3)' },
  yargs: { kb: 90, swap: 'node:util parseArgs for simple CLIs' },
  nodemon: { kb: 35, swap: 'node --watch (Node >= 18.11)' },
  bluebird: { kb: 45, swap: 'native Promises + async/await' },
  q: { kb: 15, swap: 'native Promises + async/await', deprecated: true, note: 'unmaintained; superseded by native Promises' },
  async: { kb: 35, swap: 'native async/await + Promise.all/allSettled' },
  'fs-extra': { kb: 30, swap: 'native fs — cp/rm/mkdir recursive all exist now' },
  ncp: { kb: 8, swap: 'fs.cp(src, dest, { recursive: true }) (Node >= 16.7)', deprecated: true, note: 'unmaintained' },
  cpy: { kb: 25, swap: 'fs.cp(src, dest, { recursive: true })' },
  'graceful-fs': { kb: 8, swap: 'native fs — the EMFILE bug it patched was fixed in Node >= 4' },
  'crypto-js': { kb: 40, swap: 'node:crypto (hashes, HMAC, AES all built in)' },
  md5: { kb: 4, swap: 'node:crypto createHash', deprecated: true, note: 'MD5 itself is broken for any security use' },
  sha1: { kb: 4, swap: 'node:crypto createHash', deprecated: true },
  querystring: { kb: 3, swap: 'URLSearchParams (global since Node 10)', deprecated: true, note: 'legacy Node API, documented as deprecated' },
  'left-pad': { kb: 1, swap: 'String.prototype.padStart', deprecated: true },
  glob: { kb: 20, swap: 'fs.glob (Node >= 22) or fast-glob', note: 'modern Node has native globbing' },
  webpack: { kb: 500, swap: 'esbuild or vite for most app builds', note: 'still the right call for complex module graphs' },
  through2: { kb: 6, swap: 'native stream.Transform' },
  'is-odd': { kb: 2, swap: 'n % 2 === 1 — a one-liner, not a package' },
  'is-even': { kb: 2, swap: 'n % 2 === 0 — a one-liner, not a package' },
  'is-number': { kb: 2, swap: 'Number.isFinite / !Number.isNaN — one-liners' },
  ora: { kb: 30, swap: 'a ~20-line custom spinner (ora pulls 8+ transitive deps)' },
  inquirer: { kb: 60, swap: 'node:readline/prompts or @clack/prompts for simple prompts' },
  'npm-run-all': { kb: 15, swap: 'shell && chains, or the maintained npm-run-all2 fork', deprecated: true, note: 'unmaintained since 2019' },
  xml2js: { kb: 40, swap: 'fast-xml-parser (leaner, actively maintained)' },
  'json5': { kb: 15, swap: 'JSON.parse if your inputs are actually JSON' },
  tslib: { kb: 10, swap: 'nothing if TypeScript emits helpers inline; keep it when it dedupes helpers' },
};

/** Look up a package name in the KB. Returns the entry or undefined. */
export function lookup(name) {
  return KB[name];
}
